ci: test: add tests for default install location
closes #20

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,48 +30,102 @@ jobs:
             ida_version: "9.1"
             slug: "release/9.1/ida-essential/ida-essential_91_x64linux.run"
             idat_path: "/idat"
+            default_path: "~/.local/share/applications/IDA Essential 9.1"
 
           - name: IDA 9.1 on Windows
             os: windows-latest
             ida_version: "9.1"
             slug: "release/9.1/ida-essential/ida-essential_91_x64win.exe"
             idat_path: "/idat.exe"
+            default_path: "C:\\Program Files\\IDA Essential 9.1"
 
           - name: IDA 9.1 on macOS (Intel)
             os: macos-latest
             ida_version: "9.1"
             slug: "release/9.1/ida-essential/ida-essential_91_x64mac.app.zip"
             idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Essential 9.1.app"
 
           - name: IDA 9.1 on macOS (ARM)
             os: macos-latest
             ida_version: "9.1"
             slug: "release/9.1/ida-essential/ida-essential_91_armmac.app.zip"
             idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Essential 9.1.app"
 
           - name: IDA 9.0 on Linux
             os: ubuntu-latest
             ida_version: "9.0"
             slug: "release/9.0/ida-essential/ida-essential_90_x64linux.run"
             idat_path: "/idat"
+            default_path: "~/.local/share/applications/IDA Essential 9.0"
 
           - name: IDA 9.0 on Windows
             os: windows-latest
             ida_version: "9.0"
             slug: "release/9.0/ida-essential/ida-essential_90_x64win.exe"
             idat_path: "/idat.exe"
+            default_path: "C:\\Program Files\\IDA Essential 9.0"
 
           - name: IDA 9.0 on macOS (Intel)
             os: macos-latest
             ida_version: "9.0"
             slug: "release/9.0/ida-essential/ida-essential_90_x64mac.app.zip"
             idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Essential 9.0.app"
 
           - name: IDA 9.0 on macOS (ARM)
             os: macos-latest
             ida_version: "9.0"
             slug: "release/9.0/ida-essential/ida-essential_90_armmac.app.zip"
             idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Essential 9.0.app"
+
+          # #################################################################
+          # SP releases
+          - name: IDA 9.0 SP1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.0sp1"
+            slug: "release/9.0/ida-pro/ida-pro_90sp1_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Professional 9.0sp1.app"
+
+          # #################################################################
+          # other product versions
+          - name: IDA Home 9.1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.1"
+            slug: "release/9.1/ida-home/ida-home-pc_91_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Home 9.1.app"
+
+          - name: IDA Free 9.1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.1"
+            slug: "release/9.1/ida-free/ida-free-pc_91_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Free 9.1.app"
+
+          - name: IDA Classroom 9.1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.1"
+            slug: "release/9.1/ida-classroom/ida-classroom-free_91_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Classroom 9.1.app"
+
+          - name: IDA Essential 9.1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.1"
+            slug: "release/9.1/ida-essential/ida-essential_91_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Essential 9.1.app"
+
+          - name: IDA Pro 9.1 on macOS (ARM)
+            os: macos-latest
+            ida_version: "9.1"
+            slug: "release/9.1/ida-pro/ida-pro_91_armmac.app.zip"
+            idat_path: "/Contents/MacOS/idat"
+            default_path: "/Applications/IDA Professional 9.1.app"
 
     steps:
       - name: Checkout
@@ -102,6 +156,22 @@ jobs:
         run: |
           ${{ runner.temp }}/app/ida/${{ matrix.os_ida.idat_path }} -a -A -c -t -L"${{ runner.temp }}/ida.log" -S"${{ github.workspace }}/tests/scripts/hi.py" || echo "ida: $?"
           cat "${{ runner.temp }}/ida.log"
+          if [[ ! -f "${{ runner.temp }}/ida.log" ]]; then
+            echo "ERROR: Log file does not exist"
+            exit 1
+          fi
+
+      - name: Install IDA ${{ matrix.os_ida.ida_version }} (default location)
+        run: |
+          uv run hcli ida install --download-id ${{ matrix.os_ida.slug }} --license-id ${{ secrets.IDA_LICENSE_ID }} --set-default
+          # TODO: this won't work on Windows
+          if [[ ! -d "${{ matrix.os_ida.default_path }}" ]]; then
+            echo "ERROR: Default installation path does not exist: $default_path"
+            exit 1
+          fi
+        env:
+          HCLI_API_KEY: ${{ secrets.HCLI_API_KEY }}
+          IDA_LICENSE_ID: ${{ secrets.IDA_LICENSE_ID }}
 
       - name: Run tests
         run: uv run pytest -v tests/
